sudo: required
services:
  - docker

before_install:
  - docker build -t sashanksaya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sashanksaya/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker_React"
  env: "DockerReact-env"
  bucket_name: "docker-react-app"
  bucket_path: "Docker_React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  