sudo: required
services:
  - docker

before_install:
  - docker build -t sashanksaya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sashanksaya/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "DockerReact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-132038123788"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  